server:
  port: 8010

spring:
  application:
    name: pet-clinic

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/my-realm

  docker:
    compose:
      enabled: true
      file: classpath:docker/mailpit-docker-compose.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pet_clinic
    username: user
    password: pass

  jpa:
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  #  flyway:
  #    enabled: true
  #    baseline-on-migrate: true
  #    locations: classpath:db/migration

  mail:
    host: localhost
    port: 1025
    from: info@farzan6118.com
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      username: user
      password: pass

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

keycloak:
  server-url: http://localhost:8180
  realm: my-realm
  client-id: pet-clinic
  client-secret: FOQMRj0eUxo7evJj5BWhJ0dSF8HiDB9Ja6QKgwuAy053YnzTCe5nkdBF18ochptSVxsG5Brnu0U1AsKutjmafP

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_1

  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    default-models-expand-depth: -1

system:
  default:
    uuid: 00000000-0000-0000-0000-000000000001

logging:
  level:
    root: info
    web: info
    sql: info